### ISSUE TITLE
You don't need a subfolder `Sinless-Fork`

### ISSUE THREAD

**Issue by lzblack** [gabriellemiller/Sinless-Fork#1]
If you move all files to root folder (and remove the empty folder `Sinless-Fork`), then `https://sinless-fork.herokuapp.com/proposal.html` could work.

**Comment by gabriellemiller** [comment]
fixed it! hopefully html code works now

**Comment by lzblack** [comment]
Yes, it is! Check it out now. https://sinless-fork.herokuapp.com/proposal.html
