### ISSUE TITLE
Yusra's Peer Review

### ISSUE THREAD

**Issue by ysyed1** [gabriellemiller/Sinless-Fork#4]
OK LOVE THIS !!!

Tech suggestions:
- Include title attribute in image tags
- Logo doesn't take you back to index.html - extra /a tag in link code

Content suggestions:
- Embedding social media into website, social media icon bar
- Sidebar dropdown menu ?
- LOVE the videos for recipes, maybe fitness videos too

**Comment by gabriellemiller** [comment]
Thank you for taking the time to look so deeply into my code! I will definitely embed a social media icon bar. Also good catch with the title attribute I will definitely change that!
