### ISSUE TITLE
Shiyu's Peer Review

### ISSUE THREAD

**Issue by SHIYUZHANG1** [gabriellemiller/Sinless-Fork#5]
Hello! Your website has interesting content and I love your use of canva for pictures!

Tech Suggestion:
1. Pay attention to the website element placement. Margin, padding, border and so on.
2. Try use other font family or color to emphasize some of your highlight.

Content Suggestion:
1. Highlight the meaning of "Sinless-fork". 
2. Maybe add a link of video.

**Comment by gabriellemiller** [comment]
Thank you so much! I will add a link to my videos, good catch. Good luck with your project!
