### ISSUE TITLE
Scarlet's Peer Review

### ISSUE THREAD

**Issue by sbroderick1** [gabriellemiller/Sinless-Fork#6]
I love your website! I have also gotten super into working out and cooking new recipes during quarantine and im excited to read all of your content! I love your graphics that you have so far they are super unique and really bring the whole website together. 
In terms of technical issues
1) I like the join the community button a lot just in case you didn't know right now when you click on it it comes up to an error page
2) I don't see a feedback form yet which I think has to be included 
For suggestions: 
1) For your about me, I love all the buttons like sweat check and indulge with me, maybe try and format the about me page so its more like grid style so you can see It all under the little bio
2) I know not everything is formatted yet but maybe for the other pages try and format it so there isn't as much scrolling as there is on the about me page. But again that might all change once its all formatted!
All in all, great job! I can't wait to see the finished product

**Comment by gabriellemiller** [comment]
Thank you for taking the time to look so deeply into my website! I will definitely use the grid format for my About Me page because it's a little lengthy. Also good catch with the feedback form I will definitely add that! Looking forward to seeing your website too!
